# Generated by Django 3.0.2 on 2020-02-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
