# Generated by Django 3.0.2 on 2020-02-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200131_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='IMG-20190328-WA0003_o0agDuw.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
